### PR TITLE
[fix #128] Resolve NullPointerException

### LINKED ISSUE #128: NullPointerException when clicking on Set File button (Explore Graph Paths menu)
A detailed summary of the issue goes here. 

**What steps will reproduce the problem?**

  1. Open a dictionnary-graph (like Dnum-ord)
  2. Go to explore graph paths menu
  3. Click on the Set File button

**What is the expected output?**

Set File Menu to choose the output file

**What do you see instead?**

Capture du 2019-05-17 14-40-56

Nonetheless, when we click again on the set file button, it works normally.

**More info**

- Unitex/GramLab IDE version: 3.2rc
- UnitexToolLogger version: 3.2rc

### PR DESCRIPTION
**Pull request by selgueti**
Resolve NPE when clicking on Set File button (Explore Graph Paths menu)

## Description

Fix NullPointerException when clicking on Set File button (Explore Graph Paths menu), for the first time.

Initializes sentenceDialogBox if it is not initialized in getExploreGraphOutputDialogBox method.

End of line spaces are removed using the .editorconfig file.

## Motivation and Context

[issue 128](https://github.com/UnitexGramLab/gramlab-ide/issues/128) - NullPointerException when clicking on Set File button (Explore Graph Paths menu)

## How Has This Been Tested?

This has been tested using Dnum-ch.grf.

## Type of files

- [ ] `bin`: Binary files
- [ ] `ci`: Continuous integration files
- [ ] `doc`: Documentation files
- [x] Plain-text source code files

## Level of change

- [ ] `break`: Breaking change
- [ ] `exp`: Experimental change
- [ ] `tmp`: Temporal change
- [ ] `major`: Major change
- [x] `minor`: Minor change
- [ ] `revert`: Revert a commit change
- [ ] `sec`: Vulnerability-related change
- [ ] None of the above (normal change)

## Type of change

- [ ] `deprecat`: Deprecation of a once-stable feature
- [ ] `enhance`: Enhancement in existing functionality
- [x] `fix`: Bug fix
- [ ] `feature`: New feature
- [ ] `hotfix`: Hotfix for bugs
- [ ] `refactor`: Improve coding style, comments
- [ ] `remove`: Remove a feature

## Checklist:

- [x] My code compiles
- [x] My code does not generate new warnings
- [x] My code only implements a single fix or feature
- [x] My code does not contain any changes unrelated to the fix or feature
- [x] My code follows the code style of this project
- [x] My code includes javadoc/doxygen where appropriate
- [x] My code is well factored, so that there is not repetitive code in the wild
- [ ] My code does not refactor the surrounding code unless necessary
- [x] My code does not require a change in the documentation, if so I already opened an issue to list the changes
- [x] I have read the [**CONTRIBUTING**](../.github/CONTRIBUTING.md) document
- [x] I have read the [**Pull Request/Commit Message Guidelines**](https://git.io/JuS6u)
- [x] I have given a clear and concise title to my pull request following the above guidelines
- [x] I understand that all commits on my pull request will be squashed to a single good one
- [x] All above points were checked and are marked

### CODE REVIEW

File: unitex/src/fr/umlv/unitex/config/Config.java [hunk 1]
```diff
@@ -76,7 +76,7 @@ public class Config {
      */
     private static File applicationDir;
     private static File unitexToolLogger;
-    
+
```
Comment (martinec) [inline unitex/src/fr/umlv/unitex/config/Config.java:79]: It is advised to avoid (unnecessary) spaces refactoring in a 'fix' PR. Alternatively, you should open two PRs : 1) 'refactor' and 2) 'fix' or check [here](https://stackoverflow.com/a/7149602) to learn how to add only the changes that are not white spaces.

Comment (martinec) [reply unitex/src/fr/umlv/unitex/config/Config.java:79]: ### Checklist:
   ...
- [ ] My code does not refactor the surrounding code unless necessary

...

Comment (selgueti) [reply unitex/src/fr/umlv/unitex/config/Config.java]: Thank you for this help.

File: unitex/src/fr/umlv/unitex/config/Config.java [hunk 2]
```diff
@@ -570,6 +570,8 @@ public static JFileChooser getExploreGraphOutputDialogBox() {
         exploreGraphOutputDialogBox = new JFileChooser();
         PersonalFileFilter txtFilter =new PersonalFileFilter("txt",
                                           "Text Files");
+        if (sentenceDialogBox == null)
```
Comment (martinec) [inline unitex/src/fr/umlv/unitex/config/Config.java:573]: Hint:
> Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement.

Concerning code style: 

1) projects files: follow the code style of the project
2) new files: follow the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used)

Comment (selgueti) [reply unitex/src/fr/umlv/unitex/config/Config.java:573]: I'm confused because we can see both code styles in the same file.

Comment (martinec) [reply unitex/src/fr/umlv/unitex/config/Config.java:573]: Concerning code style:
1. projects files: follow the code style of the project, with the exception of  the following recommendations of [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html):   4.1.1 (`Use of optional braces`) , 4.3 (`One statement per line`) and 4.4 (`Column limit: 100`) 
2. new files: follow the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used)

I will update the contribution guide later to include these recommendations

**Comment by martinec** [comment]
LGTM, congrats for your first contribution !

**Review by martinec — APPROVED** [review]
